kind: Deployment
apiVersion: apps/v1
metadata:
    name: mydeploy
spec:
   replicas: 3
   selector:
      matchLabels:
           env: test
   template:
       metadata:
           labels:
               env: test
   spec:
     containers:
          - name: c00
            image: loginwebapp:latest
            ports:
              - containerPort: 8080
